# Generated by Django 4.0 on 2021-12-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PCModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.TextField()),
                ('name', models.TextField(unique=True)),
                ('screen', models.FloatField()),
                ('CPU', models.CharField(max_length=20)),
                ('memory', models.CharField(max_length=20)),
                ('price', models.FloatField()),
            ],
        ),
    ]
