# Generated by Django 4.0 on 2021-12-15 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PC',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'pc',
            },
        ),
        migrations.CreateModel(
            name='Display',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('matrix_type', models.TextField()),
                ('diagonal', models.FloatField()),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='computers.pc')),
            ],
            options={
                'db_table': 'display',
            },
        ),
    ]
